- name: "Accessories"
  description: "Accessories of all sorts"
  critical: false
  hidden: false
  selected: false
  packages:
    - cheese
    - flameshot
    - liferea
    - mediainfo
    - mcomix
    - pdfarranger
- name: "Fonts"
  description: "Fonts"
  critical: false
  hidden: false
  selected: false
  packages:
    - terminus-font
- name: "Git"
  description: "Git applications"
  critical: false
  hidden: false
  selected: false
  packages:
    - gitahead-bin
    - gitg
    - gitfiend
    - gitkraken
- name: "Fun"
  description: "Fun script from ArcoLinux - great for screenshots"
  critical: false
  hidden: false
  selected: false
  packages:
    - arcolinux-meta-fun
- name: "Password Manager"
  description: "Password manager"
  critical: false
  hidden: false
  selected: false
  packages:
    - bitwarden-bin
    - enpass-bin
    - keepassxc
    - lastpass
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  packages:
    - tor-browser
    - tor
    - privoxy
- name: "Usb"
  description: "Usb writing applications"
  critical: false
  hidden: false
  selected: false
  packages:
    - etcher-bin
    - imagewriter
    - woeusb
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts-headers
    - linux-lts
